name: Documentation Fix

about: Suggest a documentation improvement or correction

labels: Documentation

---

**Describe the issue**

A clear and concise description of the issue with the documentation.

**Proposed solution**

Provide details on how you would like to improve or correct the documentation.

**Additional context**

Add any additional context or information about the documentation issue.