name: Installation Bug

about: Report an issue related to installation or setup

labels: Bug, Question

---

**Describe the issue**

A clear and concise description of the issue related to installation or setup.

**Steps to reproduce**

Steps to reproduce the issue:

1. ...
2. ...
3. ...

**Expected behavior**

A clear and concise description of what you expected to happen.

**Additional context**

Add any additional context or information about the installation bug.
