name: Issue Labeler

on:
  issues:
    types: [opened, edited]

jobs:
  label:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Label issues
        uses: actions/github-script@v4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const labels = {
              'Abandoned': [/^abandoned/i],
              'API': [/^api/i],
              'Audit': [/^audit/i],
              'Blocked': [/^blocked/i],
              'Compatibility': [/^compatibility/i],
              'Crashing': [/^crashing/i],
              'Documentation': [/^documentation/i],
              'Duplicate': [/^duplicate/i],
              'Enhancement': [/^enhancement/i],
              'Error': [/^error/i],
              'Feature request': [/^feature request/i],
              'Graphics': [/^graphics/i],
              'High severity': [/^high severity/i],
              'Low severity': [/^low severity/i],
              'Massive problem': [/^massive problem/i],
              'Medium severity': [/^medium severity/i],
              'Question': [/^question/i],
              'Stable': [/^stable/i]
            };
            
            const issue = context.issue;
            const title = issue.title.toLowerCase();
            const body = issue.body.toLowerCase();

            for (const label in labels) {
              const patterns = labels[label];
              for (const pattern of patterns) {
                if (pattern.test(title) || pattern.test(body)) {
                  console.log(`Adding label "${label}" to issue`);
                  await github.issues.addLabels({
                    owner: issue.owner,
                    repo: issue.repo,
                    issue_number: issue.number,
                    labels: [label]
                  });
                  break;
                }
              }
            }
